### ISSUE TITLE
Lingua della mappa

### ISSUE THREAD

**Issue by nemobis** [synapta/maschera-inserimento-wikidata#4]
Alla pagina https://autorizzazioni.wikilovesmonuments.it/maschera , la mappa caricata da tile.synapta.io è in inglese, per esempio "Sforza Castle" per https://www.openstreetmap.org/relation/1918 .

Vedo che è lo stesso in https://map.wikimedia.swiss/v/archives-ch-de-it-fr , quindi forse è una decisione intenzionale e il livello in italiano manca per risparmiare risorse, nel qual caso non è un problema di questa applicazione.

**Comment by alemela** [comment]
Il tile server supporta il multilingua ma non mi è chiaro come estrarle. Questa ad esempio è una libreria per gestirlo https://github.com/klokantech/openmaptiles-language ma usa mapbox-gl mentre in questo progetto usiamo leaflet.js. Per leafleat non ho trovato come farlo... per cui PR benvenute :-)
