### ISSUE TITLE
Licenza dei contributi

### ISSUE THREAD

**Issue by nemobis** [synapta/maschera-inserimento-wikidata#5]
> Cliccando il tasto accetto termini e condizioni e mi assumo la responsabilità della veridicità delle informazioni.

Ma https://foundation.wikimedia.org/wiki/Terms_of_Use/it non dice nulla su Wikidata e non mi pare nemmeno che Wikidata sia citata dalla maschera, dove si dice qualcosa del genere "nessun dato sarà salvato da questa applicazione". Bisogna citare esplicitamente e collegare la licenza CC-0 https://creativecommons.org/publicdomain/zero/1.0/deed.it così come fa il piè di pagina di https://www.wikidata.org/ .

**Comment by alemela** [comment]
Fatto: https://github.com/synapta/maschera-inserimento-wikidata/commit/59fed6de1784e86c44199cf63c7d426ac8d59afc
